/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_util_dns_DnsUtil */

#ifndef _Included_com_util_dns_DnsUtil
#define _Included_com_util_dns_DnsUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_util_dns_DnsUtil
 * Method:    getTxtRecord
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_util_dns_DnsUtil_getTxtRecord
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_util_dns_DnsUtil
 * Method:    getARecord
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_util_dns_DnsUtil_getARecord
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     com_util_dns_DnsUtil
 * Method:    getPtrRecord
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_util_dns_DnsUtil_getPtrRecord
  (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
